/*
 * bin2h - Binary to C Header Converter
 * Converts binary files to C header arrays for embedded use
 */

#include <stdio.h>
#include <string.h>

/* Simple basename implementation */
static const char* get_basename(const char *path) {
    const char *base = path;
    const char *p = path;

    while (*p) {
        if (*p == '/' || *p == '\\') {
            base = p + 1;
        }
        p++;
    }

    return base;
}

/* Convert filename to valid C identifier */
static void filename_to_identifier(const char *filename, char *identifier) {
    int i = 0;

    while (*filename && *filename != '.') {
        if ((*filename >= 'a' && *filename <= 'z') ||
            (*filename >= 'A' && *filename <= 'Z') ||
            (*filename >= '0' && *filename <= '9')) {
            identifier[i++] = *filename;
        } else {
            identifier[i++] = '_';
        }
        filename++;
    }

    identifier[i] = '\0';
}

int main(int argc, char **argv) {
    FILE *input;
    FILE *output;
    const char *input_file;
    const char *output_file;
    const char *base_name;
    char identifier[256];
    unsigned char buffer[16];
    size_t bytes_read;
    size_t total_bytes = 0;
    size_t offset = 0;
    int first = 1;

    if (argc != 3) {
        fprintf(stderr, "Usage: %s <input.bin> <output.h>\n", argv[0]);
        fprintf(stderr, "\nConverts binary file to C header array\n");
        fprintf(stderr, "Example: %s test.bin test.h\n", argv[0]);
        return 1;
    }

    input_file = argv[1];
    output_file = argv[2];

    /* Open input file */
    input = fopen(input_file, "rb");
    if (!input) {
        fprintf(stderr, "Error: Cannot open input file '%s'\n", input_file);
        return 1;
    }

    /* Get file size */
    fseek(input, 0, SEEK_END);
    total_bytes = ftell(input);
    fseek(input, 0, SEEK_SET);

    /* Open output file */
    output = fopen(output_file, "w");
    if (!output) {
        fprintf(stderr, "Error: Cannot create output file '%s'\n", output_file);
        fclose(input);
        return 1;
    }

    /* Generate identifier from base filename */
    base_name = get_basename(input_file);
    filename_to_identifier(base_name, identifier);

    /* Write header */
    fprintf(output, "/*\n");
    fprintf(output, " * Auto-generated from %s\n", base_name);
    fprintf(output, " * DO NOT EDIT - Generated by bin2h\n");
    fprintf(output, " */\n\n");
    fprintf(output, "#ifndef TEST_%s_H\n", identifier);
    fprintf(output, "#define TEST_%s_H\n\n", identifier);
    fprintf(output, "#include \"c32_types.h\"\n\n");

    /* Write array declaration */
    fprintf(output, "const uint8_t test_%s[] = {\n", identifier);

    /* Write binary data */
    while ((bytes_read = fread(buffer, 1, sizeof(buffer), input)) > 0) {
        size_t i;

        if (!first) {
            fprintf(output, ",\n");
        }
        first = 0;

        fprintf(output, "    ");
        for (i = 0; i < bytes_read; i++) {
            fprintf(output, "0x%02x", buffer[i]);
            if (i < bytes_read - 1) {
                fprintf(output, ", ");
            }
        }

        /* Add comment with offset */
        fprintf(output, "  /* 0x%04lx */", (unsigned long)offset);
        offset += bytes_read;
    }

    fprintf(output, "\n};\n\n");

    /* Write size constant */
    fprintf(output, "const uint32_t test_%s_size = %lu;\n\n", identifier, (unsigned long)total_bytes);

    /* Write footer */
    fprintf(output, "#endif /* TEST_%s_H */\n", identifier);

    /* Close files */
    fclose(input);
    fclose(output);

    printf("Generated %s:\n", output_file);
    printf("  Array name: test_%s\n", identifier);
    printf("  Size:       %lu bytes\n", (unsigned long)total_bytes);

    return 0;
}
